#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

if [ -z $OPENSHIFT_MYSQL_DB_HOST ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    exit 5
fi

# Confirm database exists, if not create it
if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -e "select * from sfj8s_assets;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
then
    echo
    echo "mporting 'lychee.sql' schema."
    echo
    /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" "$OPENSHIFT_APP_NAME" < "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/lychee.sql"
    echo
    echo "done."
    echo "=================================================="
    echo "  Lychee admin login: admin"
    echo "  Lychee admin password: adm1n"
    echo "  Don't forget to change your Lychee admin password!"
    echo "=================================================="
    echo "Don't forget to star the project at: https://github.com/gautamkrishnar/Lychee-CMS-openshift-quickstart"
else
    echo "Database found, skipping import."
fi
